### ISSUE TITLE
Any reference on funtion label_spread() in strategy()?

### ISSUE THREAD

**Issue by neverUseThisName** [deepware/deepfake-scanner#8]
In function strategy(), there's another function label_spread(). I don't understand the mechanism and can't find any reference. Can you point any to me? Thanks a lot!

**Comment by dodobyte** [comment]
since we use ensemble of models internally, predictions are averaged and the final prediction is less confident even though it's mostly correct. this is a simple function that moves prediction closer to 1 if it's already higher than 0.8.

it's actually useful for only competitions and benchmarks. here's the graph of the function.

![image](https://user-images.githubusercontent.com/30313862/127124844-99e8ed87-7d94-470e-a6cc-394e85be4a75.png)

**Comment by neverUseThisName** [comment]
That's great. Thanks a lot！
